AWSTemplateFormatVersion: '2010-09-09'
Description: API Gateway (NYC Taxi Platform)

Resources:

  TaxiApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: nyc-taxi-api

  TripsResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt TaxiApi.RootResourceId
      PathPart: trips
      RestApiId: !Ref TaxiApi

Outputs:
  ApiId:
    Value: !Ref TaxiApi
