AWSTemplateFormatVersion: '2010-09-09'
Description: Databases layer (RDS + DynamoDB)

Resources:

  # ======================
  # DynamoDB (REALTIME FIX)
  # ======================
  RealtimeEventsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: realtime_events
      BillingMode: PAY_PER_REQUEST

      AttributeDefinitions:
        - AttributeName: taxi_id
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S

      KeySchema:
        - AttributeName: taxi_id
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE

  # ======================
  # RDS SECURITY GROUP
  # ======================
  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow PostgreSQL access
      VpcId:
        Fn::ImportValue: MainVPC

      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: 0.0.0.0/0

  # ======================
  # RDS POSTGRES (FREE TIER SAFE)
  # ======================
  TaxiPostgres:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: nyc-taxi-db
      Engine: postgres
      DBInstanceClass: db.t3.micro
      AllocatedStorage: 20
      StorageType: gp2

      MasterUsername: postgres

      # ⚠️ DEMO ONLY (OK school, not prod)
      MasterUserPassword: !Sub "{{resolve:secretsmanager:nyc-db-password:SecretString}}"

      PubliclyAccessible: true

      VPCSecurityGroups:
        - !Ref RDSSecurityGroup

Outputs:
  RDSAddress:
    Value: !GetAtt TaxiPostgres.Endpoint.Address

  DynamoTable:
    Value: !Ref RealtimeEventsTable
