AWSTemplateFormatVersion: '2010-09-09'
Description: Kafka EC2 (Free Tier)

Parameters:
  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName

Resources:

  KafkaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Kafka access
      VpcId:
        Fn::ImportValue: MainVPC

      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

        - IpProtocol: tcp
          FromPort: 9092
          ToPort: 9092
          CidrIp: 0.0.0.0/0

  KafkaInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId: ami-0f7cd40eac2214b37

      KeyName: !Ref KeyPairName

      SubnetId:
        Fn::ImportValue: PublicSubnetId

      SecurityGroupIds:
        - !Ref KafkaSecurityGroup

      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          yum install java-17-amazon-corretto -y

          wget https://downloads.apache.org/kafka/3.6.0/kafka_2.13-3.6.0.tgz
          tar -xzf kafka_2.13-3.6.0.tgz
          mv kafka_2.13-3.6.0 /opt/kafka

          echo "Kafka installed"

Outputs:
  KafkaPublicIP:
    Value: !GetAtt KafkaInstance.PublicIp
