AWSTemplateFormatVersion: '2010-09-09'
Description: NYC Taxi Data Lake Storage

Resources:

  DataLakeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: nyc-taxi-platform

      VersioningConfiguration:
        Status: Enabled

      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

      LifecycleConfiguration:
        Rules:
          - Id: BronzeRetention
            Status: Enabled
            ExpirationInDays: 30

Outputs:
  BucketName:
    Value: !Ref DataLakeBucket
    Export:
      Name: DataLakeBucketName
