name: Setup Glue Jobs

on:
  workflow_dispatch:

jobs:
  setup-glue:
    name: Upload scripts S3 + Create Glue Jobs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-3

      - name: Upload Glue scripts to S3
        run: |
          aws s3 cp glue_jobs/bronze_to_silver.py s3://nyc-taxi-platform/scripts/bronze_to_silver.py
          aws s3 cp glue_jobs/silver_to_gold.py s3://nyc-taxi-platform/scripts/silver_to_gold.py
          aws s3 cp glue_jobs/gold_to_rds.py s3://nyc-taxi-platform/scripts/gold_to_rds.py
          echo "Scripts uploaded"

      - name: Download PostgreSQL JDBC driver
        run: |
          wget -q https://jdbc.postgresql.org/download/postgresql-42.7.3.jar
          aws s3 cp postgresql-42.7.3.jar s3://nyc-taxi-platform/scripts/postgresql-42.7.3.jar
          echo "JDBC driver uploaded"

      - name: Create or update bronze_to_silver
        run: |
          if aws glue get-job --job-name bronze_to_silver 2>/dev/null; then
            aws glue update-job --job-name bronze_to_silver --job-update '{
              "Role": "nyc-taxi-glue-role",
              "Command": {"Name":"glueetl","ScriptLocation":"s3://nyc-taxi-platform/scripts/bronze_to_silver.py","PythonVersion":"3"},
              "DefaultArguments": {"--job-language":"python","--TempDir":"s3://nyc-taxi-platform/tmp/","--enable-metrics":"true"},
              "GlueVersion": "4.0", "NumberOfWorkers": 2, "WorkerType": "G.1X", "Timeout": 60
            }'
          else
            aws glue create-job --name bronze_to_silver \
              --role nyc-taxi-glue-role \
              --command '{"Name":"glueetl","ScriptLocation":"s3://nyc-taxi-platform/scripts/bronze_to_silver.py","PythonVersion":"3"}' \
              --default-arguments '{"--job-language":"python","--TempDir":"s3://nyc-taxi-platform/tmp/","--enable-metrics":"true"}' \
              --glue-version "4.0" --number-of-workers 2 --worker-type "G.1X" --timeout 60
          fi

      - name: Create or update silver_to_gold
        run: |
          if aws glue get-job --job-name silver_to_gold 2>/dev/null; then
            aws glue update-job --job-name silver_to_gold --job-update '{
              "Role": "nyc-taxi-glue-role",
              "Command": {"Name":"glueetl","ScriptLocation":"s3://nyc-taxi-platform/scripts/silver_to_gold.py","PythonVersion":"3"},
              "DefaultArguments": {"--job-language":"python","--TempDir":"s3://nyc-taxi-platform/tmp/","--enable-metrics":"true"},
              "GlueVersion": "4.0", "NumberOfWorkers": 2, "WorkerType": "G.1X", "Timeout": 60
            }'
          else
            aws glue create-job --name silver_to_gold \
              --role nyc-taxi-glue-role \
              --command '{"Name":"glueetl","ScriptLocation":"s3://nyc-taxi-platform/scripts/silver_to_gold.py","PythonVersion":"3"}' \
              --default-arguments '{"--job-language":"python","--TempDir":"s3://nyc-taxi-platform/tmp/","--enable-metrics":"true"}' \
              --glue-version "4.0" --number-of-workers 2 --worker-type "G.1X" --timeout 60
          fi

      - name: Create or update gold_to_rds
        run: |
          ARGS=$(cat << JSONEOF
          {
            "--job-language": "python",
            "--TempDir": "s3://nyc-taxi-platform/tmp/",
            "--enable-metrics": "true",
            "--extra-jars": "s3://nyc-taxi-platform/scripts/postgresql-42.7.3.jar",
            "--RDS_HOST": "nyc-taxi-db.criow0g6edvj.eu-west-3.rds.amazonaws.com",
            "--RDS_PASSWORD": "${{ secrets.RDS_PASSWORD }}"
          }
          JSONEOF
          )
          if aws glue get-job --job-name gold_to_rds 2>/dev/null; then
            aws glue update-job --job-name gold_to_rds --job-update \
              "{\"Role\":\"nyc-taxi-glue-role\",\"Command\":{\"Name\":\"glueetl\",\"ScriptLocation\":\"s3://nyc-taxi-platform/scripts/gold_to_rds.py\",\"PythonVersion\":\"3\"},\"DefaultArguments\":$ARGS,\"Connections\":{\"Connections\":[\"nyc-rds-connection\"]},\"GlueVersion\":\"4.0\",\"NumberOfWorkers\":2,\"WorkerType\":\"G.1X\",\"Timeout\":60}"
          else
            aws glue create-job --name gold_to_rds \
              --role nyc-taxi-glue-role \
              --command '{"Name":"glueetl","ScriptLocation":"s3://nyc-taxi-platform/scripts/gold_to_rds.py","PythonVersion":"3"}' \
              --default-arguments "$ARGS" \
              --connections '{"Connections":["nyc-rds-connection"]}' \
              --glue-version "4.0" --number-of-workers 2 --worker-type "G.1X" --timeout 60
          fi

      - name: Done
        run: aws glue list-jobs --query 'JobNames'
